### ISSUE TITLE
Update Role to work with Ubuntu 22.04 Rocky Linux 9

### ISSUE THREAD

**Issue by JulianHn** [ome/ansible-role-postgresql-client#7]
Just to avoid multiple people taking the same role to update (cf. https://github.com/ome/omero-server-docker/issues/79 / https://github.com/ome/omero-web-docker/issues/74) I am also opening an issue here, so people can claim that specific role to work on.

I would be available to work on this beginning of next week, so if no one wants to call dibs before, I would take on the updates of this role.

// Julian

**Comment by jburel** [comment]
See https://github.com/ome/ansible-role-postgresql-client/pull/8
